# Site settings
title: corey elliott design
email: corey.elliott@mac.com
description: > # this means to ignore newlines until "baseurl:"
  Portfolio & personal site for Corey Elliott - Austin based UI and visual designer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cedsgn.com/" # the base hostname & protocol for your site
dribbble_username: cedsgn
instagram_username: cedsgn
github_username:  ellcorey
linkedin_username: coreyaelliott
twitter_username: cedsgn
main_email: corey@cedsgn.com

collections:
 projects:
  output: true
  permalink: /work/:path/.html

# Build settings
markdown: kramdown
highlighter: pygments