# Site settings
title: corey elliott design
email: corey.elliott@mac.com
description: > # this means to ignore newlines until "baseurl:"
  Portfolio & personal site for Corey Elliott - Austin based UI and visual designer.
baseurl: "/corey_elliott_design" # the subpath of your site, e.g. /blog/
url: "http://ellcorey.github.io/" # the base hostname & protocol for your site
dribbble_username: ellcorey
instagram_username: ellcorey
github_username:  ellcorey
linkedin_username: coreyaelliott
twitter_username: cedsgn

collections:
 projects:
  output: true
  permalink: /work/:path/.html

# Build settings
markdown: kramdown
highlighter: pygments